import { supabase } from '../supabaseClient';
import { IInventoryService } from '../inventoryService';
import { SparePart, PartsRequest } from '../../../types/inventory';

export class InventorySupabaseService implements IInventoryService {

    // --- Mappers ---
    private mapDBToPart(record: any): SparePart {
        return {
            id: record.id,
            partNumber: record.sku,
            name: record.name,
            category: record.category,
            currentStock: record.current_stock,
            minStock: record.minimum_stock,
            maxStock: record.maximum_stock || 0, // Ensure maxStock is handled if added to DB, or default
            // reorderPoint: record.reorder_point, // Type definition might not have this, check types/inventory.ts
            location: record.location_code,
            cost: record.unit_cost,
            // currency: record.currency,
            // supplier: record.supplier,
            // leadTimeDays: record.lead_time_days
            // photoUrl: record.photo_url // If exists
            createdAt: record.created_at
        } as SparePart;
    }

    private mapPartToDB(part: Partial<SparePart>): any {
        return {
            // id: part.id, // generated
            sku: part.partNumber,
            name: part.name,
            category: part.category,
            current_stock: part.currentStock,
            minimum_stock: part.minStock,
            maximum_stock: part.maxStock,
            // reorder_point: part.reorderPoint,
            location_code: part.location,
            unit_cost: part.cost,
            // currency: part.currency,
            // supplier: part.supplier,
            // lead_time_days: part.leadTimeDays
            // created_at: part.createdAt // Usually auto-generated by DB
        };
    }

    // --- Parts API ---

    async getAllParts(): Promise<SparePart[]> {
        const { data, error } = await supabase
            .from('spare_parts')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;
        return data.map(this.mapDBToPart);
    }

    async createPart(partData: Omit<SparePart, 'id' | 'currentStock'> & { initialStock?: number }): Promise<SparePart> {
        const dbPayload = this.mapPartToDB({
            ...partData,
            currentStock: partData.initialStock || 0
        });

        // Generate ID
        const id = crypto.randomUUID();
        dbPayload.id = id;

        const { data, error } = await supabase
            .from('spare_parts')
            .insert(dbPayload)
            .select()
            .single();

        if (error) throw error;
        return this.mapDBToPart(data);
    }

    async updatePart(updatedPart: SparePart): Promise<SparePart> {
        const dbPayload = this.mapPartToDB(updatedPart);

        const { data, error } = await supabase
            .from('spare_parts')
            .update(dbPayload)
            .eq('id', updatedPart.id)
            .select()
            .single();

        if (error) throw error;
        return this.mapDBToPart(data);
    }

    async addStock(partId: string, quantity: number, relatedDocId?: string): Promise<void> {
        // 1. Get current stock
        const { data: part, error: getError } = await supabase
            .from('spare_parts')
            .select('current_stock')
            .eq('id', partId)
            .single();

        if (getError) throw getError;

        const newStock = (part.current_stock || 0) + quantity;

        // 2. Update stock
        const { error: updateError } = await supabase
            .from('spare_parts')
            .update({ current_stock: newStock })
            .eq('id', partId);

        if (updateError) throw updateError;

        // TODO: Insert into 'inventory_transactions' table when it exists
    }

    async bulkCreate(parts: Omit<SparePart, 'id'>[]): Promise<void> {
        const dbPayloads = parts.map(part => {
            const payload = this.mapPartToDB(part);
            payload.id = crypto.randomUUID();
            return payload;
        });

        const { error } = await supabase
            .from('spare_parts')
            .insert(dbPayloads);

        if (error) throw error;
    }

    // --- Requests API (Not Implemented in DB yet) ---

    async getAllRequests(): Promise<PartsRequest[]> {
        console.warn('getAllRequests: Not implemented in Supabase yet');
        return [];
    }

    async createRequest(requestData: any): Promise<PartsRequest> {
        throw new Error('createRequest: Features not available in Supabase mode yet');
    }

    async deliverParts(requestId: string, itemsToDeliver: any[], receiverId?: string): Promise<PartsRequest> {
        throw new Error('deliverParts: Features not available in Supabase mode yet');
    }

    async closeRequest(requestId: string): Promise<PartsRequest> {
        throw new Error('closeRequest: Features not available in Supabase mode yet');
    }

    async deleteRequest(requestId: string): Promise<void> {
        throw new Error('deleteRequest: Features not available in Supabase mode yet');
    }

    async updateRequest(updatedRequest: PartsRequest): Promise<PartsRequest> {
        throw new Error('updateRequest: Features not available in Supabase mode yet');
    }

    async savePurchaseRequest(requestId: string, purchaseRequest: any): Promise<PartsRequest> {
        throw new Error('savePurchaseRequest: Features not available in Supabase mode yet');
    }
}
